apiVersion: application.giantswarm.io/v1alpha1
kind: Catalog
metadata:
  labels:
    application.giantswarm.io/catalog-visibility: internal
  name: kuba-test-catalog
  namespace: giantswarm
spec:
  description: kuba-test-catalog
  logoURL: "https://avatars.githubusercontent.com/u/4587658?v=4"
  storage:
    URL: oci://giantswarmpublic.azurecr.io/
    type: helm
  title: kuba-test-catalog
